### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/TimelineExtension#12]
As the title says, before this extension can be published to the Chrome and Firefox stores, we need a logo (among other things). 

Any ideas?

**Comment by dwm1909** [comment]
How come that manifest is missing 

  "icons": { 
	"128": "---",
	"48": "---",
	"16": "---"
  }

For have any icon for the app?

**Comment by th3an7** [comment]
What about something like this? It's made on the spot and it's just a proposal so the quality is sh** :P
![What about something like this?](https://i.imgur.com/Ls71XV6.png)

**Comment by dwm1909** [comment]
its also to big the menu icon is 16x16 for Chrome the background should also be transparent, have some extention my self and i have find out its like the hardest part get good engout is the icon. 

best would mabye do some icon some look like the icon for Windows Timeline? 

Mabye a circel or someting and have some looks of this. 
![222](https://user-images.githubusercontent.com/9989514/42641347-a7a93538-85f4-11e8-864c-ac19da85a9ff.jpg)

**Comment by th3an7** [comment]
That's why I said it's just a proposal... If I'd made it 16x16 you wouldn't see shit...
That black "thing" next to logos IS timeline logo - it's just slightly modified (stretched, deleted "slider")...

What about just one logo but it's in place of that rectangle in slider?

**Comment by dwm1909** [comment]
i think its simplest in that way one logo, some easy explaine the function, becouse its not relly a extention you gonna use to open i guess most people gonna hidde it and just let it do the job. 

People like only gonna watch that logo frome the Store for downloads 

Retangle, or a Circel should be great.

**Comment by th3an7** [comment]
What about this:
![White background](https://i.imgur.com/cz826Xx.png)
![Black background](https://i.imgur.com/LVX8FGd.png)

There is no transparency since I don't think it's needed much (it can be added tho)...

**Comment by da2x** [comment]
@th3an7, You can’t use Chrome’s icon. It’s a Google trademark. The extension also works for more than just one browser. It would also look incredibly squashed in 16x16 px.

**Comment by da2x** [comment]
Cortana-esque blue circle with clock hands out of the middle? (Time/history + Cortana/Graph)

**Comment by th3an7** [comment]
[Cortana is trademarked](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/en-us.aspx)

In that case you can't really do anything from already made "assets" without breaking TMs - you'd have to make every single thing and color yourself without basing on something (unless it's fair use)...

**Comment by da2x** [comment]
I said Cortana-esque. Change the color and size slightly. Microsoft can’t trademark the generic shape and color of a simple circle.

**Comment by da2x** [comment]
Sizes:

* Chrome browserAction: 16, 32
* Firefox browserAction: 19, 38
* Icon: 64, 128, 256, svg

**Comment by da2x** [comment]
I’ll make a quick icon and add it as a placeholder.

**Comment by DominicMaas** [comment]
Sounds good!

**Comment by da2x** [comment]
https://github.com/DominicMaas/TimelineExtension/blob/f6d0b66ea03bb55322a8438389042e889e5528ad/images/icon_256.png
