### ISSUE TITLE
Firefox clientId has wrong redirect URL

### ISSUE THREAD

**Issue by da2x** [DominicMaas/TimelineExtension#16]
`identity.getRedirectURL()`  endpoint is different in `browser.identify` than `chrome.identity`.

Please update the OAuth2 flow registration for the Firefox client ID to expect the following redirect URL:

    https://<firefox-extension-id>.extensions.allizom.org/

(Mozilla backwards)

**Comment by DominicMaas** [comment]
The OAuth2 details are currently setup to use the following redirect url: https://276d8a16db76c49a921bde37bdbe15ef537122f7.extensions.allizom.org/

This is the extension id for my machine, I'm unsure on how to make is consistent without publishing the extension first (same issue with Google Chrome).

**Comment by DominicMaas** [comment]
Looks like there is a way to keep is consistent on Chrome: https://developer.chrome.com/apps/app_identity#copy_key

**Comment by da2x** [comment]
Add to manifest:

```
"applications": {
  "gecko": {
    "id": "{0f128503-b26e-4af4-ba56-e42fcdc7bcad}",
    "strict_min_version": "60.0"
  }
}
```

**Comment by DominicMaas** [comment]
I had just found it before, committed the changes. Could you confirm that your redirect url matches "https://5bed674f74ec59875d4860fbe854e945b81b4dac.extensions.allizom.org/"? (it gets logged to the console).

**Comment by da2x** [comment]
It worked absolutely beautifully. So, … I guess this makes Firefox the new preferred extension development platform for this project.

**Comment by DominicMaas** [comment]
Awesome, I'll stick with Chrome so we can catch any issues that may occur between browsers.
