### ISSUE TITLE
Access Token Expiration

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/TimelineExtension#20]
The access token expires after a set amount of time, the current method of refreshing the token (log in from the background) does not work. Ideally there should be a way to refresh the token without requiring a client secret.

I'll update this with any more information that I find.

**Comment by da2x** [comment]
Client secret is "only required for web apps". An extension is considered to be a native app.

https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_user#5-use-the-refresh-token-to-get-a-new-access-token

**Comment by da2x** [comment]
Note that you must send a refresh token and not the main auth token.

**Comment by DominicMaas** [comment]
I see, I'll re-write the login code to grab and store the refresh token, then update the activity method which handles 401s to grab a new access token using the refresh token.

**Comment by da2x** [comment]
You need to request offline_access permissions. Then you should receive a second refresh_token along with the access_token. Store both tokens and use the refresh_token when renewing tokens; update both tokens in response to token renewal.

https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference#remarks-13

**Comment by da2x** [comment]
Oh, and make sure to call background.js:Logout() if renewal fails to update the UI and clear out any stored tokens.

**Comment by DominicMaas** [comment]
I think it may be fixed, but I'll have to wait till the token expires. As a by product, we now have the users email, so that can be displayed on the UI if you want (as suggested before).

**Comment by da2x** [comment]
Use `extension.getURL()` to get the extension’s `chrome-extension://<extension-id>`. Should work without any other changes in Firefox’s `identity.launchWebAuthFlow()` but I’m not sure about Chrome.

**Comment by da2x** [comment]
Setting up a redirect from chrome-extension:// back to the URL Chrome expects might just work around that issue. From reading Chrome's documentation, they have to use the expected URL. This might not actually be the case, though.

**Comment by DominicMaas** [comment]
Looks like this is heading in the right direction. Chrome ends up giving me `"Unchecked runtime.lastError while running identity.launchWebAuthFlow: Authorization page could not be loaded."` when using `chrome-extension://meokcjmjkobffcgldbjjklmaaediikdj/` as the redirect url. 

Is there maybe a way to create a custom `launchWebAuthFlow`? Open up a new window or something, user logs in, Microsoft redirects to `chrome-extension://meokcjmjkobffcgldbjjklmaaediikdj/provider-login` or `moz-extension://e80d8f57-193a-4382-96d6-83f42a8434e3/provider-login` and we somehow listen to any requests going to `{id}/provider-login?code=xxxxx`.

**Comment by da2x** [comment]
Chrome won’t allow a webpage to redirect to a chrome-extension URI. Not sure how to work around that.

**Comment by da2x** [comment]
Maybe this is useful?
https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji?hl=en

**Comment by DominicMaas** [comment]
I did take a look into it, used some fancy native APIs. I'll continue work on the implicit flow, cause I think I can get it to work, just maybe passing through the wrong parameters.

**Comment by DominicMaas** [comment]
Okay I might try this: We use the web flow which requires a client secret. The user logs in and we grab the code, I then call an Azure function (which knows the client secrets) that returns the access token and refresh token, we store these in local storage.

When the access token expires, we call another Azure function which takes in a client id, refresh token (and access token?) and returns a new valid access token which we save.

I'd be surprised if the functions go above 2 cents per month, so cost is a non-issue. I'll also create a new branch which will contain the code for the functions.

**Comment by da2x** [comment]
That can’t be the right solution. You’d get access to everyone’s accounts and activity data. You don’t want that (GDPR) and users’ won’t want that. Have you reached out to Microsoft?

**Comment by DominicMaas** [comment]
But I won't, the function acts like a wrapper. 

It calls the token endpoint (with the client secret) and returns the result to the extension. Probably under 10 lines of code. So instead of storing the client secret in the source code, It's stored in the function, all the same code is called (and if people are worried, the code is under the "auth-backend" branch).

I'll try get the code published soon so you can see what I mean.

**Comment by DominicMaas** [comment]
New system is implemented and it looks like token refreshing works beautifully, just a minor issue with timing, but I'll fix that shortly. I know it's not ideal, but most people just seem to end up writing their own backend wrapper when they encounter this issue.
