### ISSUE TITLE
Loading devices list takes 15 seconds

### ISSUE THREAD

**Issue by da2x** [DominicMaas/TimelineExtension#30]

**Comment by DominicMaas** [comment]
This is fully dependent on the Microsoft Graph (takes 5 seconds for me), but what I'll do is load the devices list on startup / log in and cache it. When you view the list of devices it will show the cached versions (but also refresh the cache in the background.

**Comment by DominicMaas** [comment]
The devices are now loaded when the extension starts and when the user logs in, these are cached (`userDevices` in `background.ts`). When you you view your device list, it will load from the cache and then refresh the cache .

I'll also add a refresh button to the menu in case someone wants to manually get the latest items.
