### ISSUE TITLE
manifest applications unknow and give out error. 

### ISSUE THREAD

**Issue by dwm1909** [DominicMaas/TimelineExtension#32]
in the manifest.json the applications is a wrong command for Chrome and its give you a error messages. 

its noting some breaking the extention but may be fixt for remove the error line 
![error](https://user-images.githubusercontent.com/9989514/42728068-45e857a6-87b2-11e8-9b23-5887bc193f3f.png)

**Comment by tbergeron** [comment]
I cannot load the unpackaged extension anymore as well. Here is what I'm getting:

https://cl.ly/3x0X133R0W2d

**Comment by dwm1909** [comment]
Everything working its just that applications is a command some dosent support by Chrome is unknow for it so its dosent relly do anything more that give out error.

**Comment by DominicMaas** [comment]
@tbergeron The actual extension is located in the 'extension' folder not the root folder.

@dwm1909 Don't worry about the error, it does not affect the extension. It's complaining about the 'application' field in the manifest, which is required for the Firefox extension to work.

They key field is crucial for the extension to work, just keep them both there, the extension will not be affected.

**Comment by DominicMaas** [comment]
Closing this as I've mentioned the fixes above.
