### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by 810** [DominicMaas/TimelineExtension#33]
I would also see a Edge version, because of the project rome feature.

**Comment by DominicMaas** [comment]
Should be possible. The extension would probably require a rename to make more sense.

**Comment by da2x** [comment]
Roadblock: Edge doesn’t support `browser.identity`.

**Comment by dwm1909** [comment]
da2x: 
Edge doesn’t support browser.identity.

Not yet atlest but is under work, i guess he questens is for a release when its working. 

identity | Used to get an OAuth2 authorization code or access token. | Under consideration
So should guess its a release for RS5 Edge is normaly fast include APIs.

**Comment by DominicMaas** [comment]
Platform updates like that are tied into the OS because the engine is. Many applications are built on the Edge engine (PWAs, WebViews & JavaScript apps).

Since it's required for https://github.com/DominicMaas/TimelineExtension/issues/37 I'll built an alternate login system for these platforms.

**Comment by da2x** [comment]
Edge specific icon sizes:
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys#browser_action-or-page_action-keys

**Comment by 810** [comment]
Do you want to create a new rep or new branch for it, so we can help for the edge extension

**Comment by DominicMaas** [comment]
I'll use the same repo / master branch. Planning on just adding checks to hide buttons that are not supported on Edge, and before timeline activity send, check that the user is not using Edge.

**Comment by DominicMaas** [comment]
I'm sure you have heard the news about the future of Edge. I'll wait until the new Edge Preview to see how they are going to handle extensions.

**Comment by 810** [comment]
Yes, its a good move, we can now use the chrome extension for it.
