### ISSUE TITLE
Sign in button never responds on Firefox for Android

### ISSUE THREAD

**Issue by saschanaz** [DominicMaas/TimelineExtension#37]
![screenshot_20180715-225505](https://user-images.githubusercontent.com/3396686/42734679-2d1c9d46-8883-11e8-9bb9-f79a34d8093e.png)

I can access the menu but tapping the button doesn't open anything. Does the extension only work on Windows browsers?

**Comment by da2x** [comment]
`browser.identity` API is unavailable in Firefox for Android. (I could swear that I checked this earlier.) It’s not on any roadmap or compat tables, so it actually looks like Mozilla just forgot to implementent it.

Looks like an alternative loign method is needed to solve this and #33.

**Comment by saschanaz** [comment]
Hmm, just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1475887.

**Comment by DominicMaas** [comment]
I'm merging this issue with #43. Feel free to track progress there.
