### ISSUE TITLE
Disable sending activities when in incognito/inprivate mode.

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/TimelineExtension#39]
If you allow the extension to run in incognito mode, it will still sync the activities. I don't see any reason why someone would want the activities synced in incognito mode (could add a toggle if really needed).

Any APIs to check if the window is in incognito/inprivate mode?

**Comment by DominicMaas** [comment]
Looks like it's not that easy (by design I guess), but some people seem to mention activities being synced when in private mode. I assume they have specifically enabled to extension to work in private mode.

**Comment by da2x** [comment]
I can’t test this now, but `sendMessage`’s sender’s `tab` object should contain whether the tab is private or not. This should work in all browsers.

**Comment by da2x** [comment]
Yes, `onMessage.sender.tab.incognito`.

**Comment by DominicMaas** [comment]
This should be fixed, but I cannot test in Firefox at the moment.

**Comment by da2x** [comment]
The fix in ba9c0b4 should work in absolutely every browser.
