### ISSUE TITLE
Extension Name

### ISSUE THREAD

**Issue by da2x** [DominicMaas/TimelineExtension#4]
Hi, please consider a more generic name for the extension. It also works in other browsers like Firefox. Maybe BrowserTimeline? or WebTimeline? RecordWebHistoryInMicrosoftGraph would be more precise but doesn’t really roll off the tongue.

**Comment by DominicMaas** [comment]
Good idea. WebTimeline may be good (as the full extension name could become "Windows Timeline for Web"). But that name kind if implies that this extension brings Windows Timeline to the web, which is not true.

"Browser Timeline" may also work, but whichever name, I agree that we need to drop the "Chrome" branding.

**Comment by JimHinson** [comment]
I think browser timeline is headed in the right direction, but perhaps too generic?

How about "Windows Timeline Support" ?

**Comment by DominicMaas** [comment]
"Windows Timeline Support" works, gets straight to the point. I think we need to keep "Windows Timeline" in the title anyway, so users know what type of "timeline" this extension is for, or if they are specifically searching for Windows Timeline support, they should see this extension.

**Comment by da2x** [comment]
@DominicMaas you should probably rename the repository before it attracts too many in-links under the old name. Change it from ChromeTimeline to TimelineExtension then you can decide on the user-facing branding later.

**Comment by DominicMaas** [comment]
There's already a fair amount of links linking to this repository, I'll rename it and create a new repo of the old name, telling users to come here.

**Comment by DominicMaas** [comment]
Alright, I've switched it over to https://github.com/DominicMaas/TimelineExtension

**Comment by DominicMaas** [comment]
I've gone with "Windows Timeline Support", thanks all for the ideas!
