### ISSUE TITLE
Chrome not working at all

### ISSUE THREAD

**Issue by maxrom** [DominicMaas/TimelineExtension#40]
I've installed it from Chrome Web Store and signed in with the same Microsoft account as I use with Windows, but my Timeline continues to only show PDFs I've opened with Chrome and not websites. Have I missed something?

**Comment by DominicMaas** [comment]
There is an issue tracking this problem. I've not narrowed it down, but I think certain timezones may be the issue. What time zone are you in?

**Comment by maxrom** [comment]
US Eastern.

**Comment by tbergeron** [comment]
I have similar issues, it doesn't seem to work right, it shows somee pages but without page titles, instead of titles it shows a number. Like for this issue it shows only "40" instead of "Chrome not working at all...".

Also in Eastern timezone (Toronto).

**Comment by DominicMaas** [comment]
Duplicate of #36, feel free to continue the discussion over there. I'll take note of the time zones.
