### ISSUE TITLE
Logging not working in Chrome 67 for Windows 7

### ISSUE THREAD

**Issue by ChrisdelaC** [DominicMaas/TimelineExtension#47]
Hi everyone!

Great idea and nice work! I logged in successfully using my Microsoft account in Chrome 67 for Windows 10, but I tried to do the same in Windows 7 and it's not working.

Is there any limitation to make the extension work in OS's that don´t support the Windows Timeline? For example, if I want to sync my history between different computers and different SO's.

Thanks in advance.

**Comment by ChrisdelaC** [comment]
I am logged in now, but it seems that login window isn't showing after one click or something like that.

Just an off-topic question before closing this issue, why the extension saves any page in Windows Timeline after 8 seconds by default? It's the same for Microsoft Edge?

Thanks!

**Comment by DominicMaas** [comment]
This extension should work on Windows 7 (it connects to the Microsoft Graph and not your computer). Are you logged in with the same Microsoft Account on both browser extensions? It should work.

"I am logged in now, but it seems that login window isn't showing after one click or something like that." - What do you mean? Don't quite understand.

This extension only saves pages in Windows Timeline after 8 seconds to try remove some of the mess generated by redirect urls, short urls, logins etc. I'm not sure what Microsoft Edge does.

**Comment by ChrisdelaC** [comment]
Hi @DominicMaas, thanks for your reply.

Yes, I am logged in now, it's just that I had to click several times in the extension's login button for the login window to be displayed in Windows 7. The login window was displayed immediately using Windows 10.

"This extension only saves pages in Windows Timeline after 8 seconds to try remove some of the mess generated by redirect urls, short urls, logins etc." Nice, thanks for the explanation.

**Comment by DominicMaas** [comment]
I see, yeah that looks like a Chome issue (can take a second or two to appear on my machine).
And no worries.
