### ISSUE TITLE
Chrome User Profile support

### ISSUE THREAD

**Issue by cavla** [DominicMaas/TimelineExtension#51]
Would it be possible to support [Chrome User Profile](https://support.google.com/chrome/answer/2364824) ? 

Let's say i install the extension on 3 different chrome user profiles and login with the same MS account. 
My activities from those 3 profiles would be sent to MS (together with the profile info) and from the timeline clicking an item would open the link in the right chrome profile.  
Not sure if i'm clear. 

(thanks for the excellent work)

**Comment by cavla** [comment]
I'm not sure but in the extension "[permissions](https://developer.chrome.com/extensions/declare_permissions)" it can be declared "identity" to give your extension access to the [chrome.identity API](https://developer.chrome.com/apps/identity) and then get the AccountInfo/ProfileUserInfo. Can this be used?

**Comment by DominicMaas** [comment]
As said above, this is not really possible, and would require a lot of work to get it using if possible.
