### ISSUE TITLE
Open Page on Android not working

### ISSUE THREAD

**Issue by TheWhiteGandalf** [DominicMaas/TimelineExtension#53]
Working page on Android is not working.
There is a grey circle in front of it instead a green one.

**Comment by DominicMaas** [comment]
Grey circle means the state of the device is unknown (green means online and red means offline). I've emailed the Project Rome team about why mobile devices are always unknown and don't work.

This is an issue in their end, and not mine, sorry.

**Comment by TheWhiteGandalf** [comment]
Thanks. I hope they fix it 😄
