### ISSUE TITLE
Not installed properly from google sync

### ISSUE THREAD

**Issue by ScottKillen** [DominicMaas/TimelineExtension#56]
If I install this on one device and then apps are synced. I got to another device and the app is "installed", but it does not work because no Microsoft login token is set up. I must uninstall and reinstall on the second device to generate the necessary Microsoft credentials on that device.

Expected behavior would be that the app would detect that the credentials are missing and reauthorize for that device.

**Comment by dwm1909** [comment]
You can not sync the logins detaljs for sync, the apps will install with every google account, but you have to sign into microsoft with every singel computer becouse that detaljs and tookens dosent sync, and that should as well be very hige chance for EU to sue Google for privacy issues if they cold and wanted to sync another companyes detaljs for sign in by it self.

**Comment by ScottKillen** [comment]
@dwm1909 Yes. Thank you.

My issue is that when the extension is installed by Google Sync, I am never given the opportunity to sign in on that machine...I must uninstall and then manually reinstall the extension to get the opportunity to log into Microsoft. The extension should, _regardless of how it came to be installed_, detect that it has not logged into Microsoft and present the opportunity to do so.

**Comment by dwm1909** [comment]
Did work fine for me so guess is some issues on you chrome in some way.

**Comment by ScottKillen** [comment]
Thanks @maximdorko

**Comment by dwm1909** [comment]
That issues hade i also need to click many times for login i was thinking was something with Chrome some did make it popup

**Comment by da2x** [comment]
The token or login status isn’t synced. However, the configured minimum time on page is synced.
