### ISSUE TITLE
Safari Support?

### ISSUE THREAD

**Issue by hazbeen** [DominicMaas/TimelineExtension#57]
Would you consider releasing a version of this extension for Safari on macOS?

I work in a mixed OS environment and already use it with Chrome, Opera, Vivaldi & Firefox on Windows (which covers all my favourite browsers!) but sometimes I do use Safari on a Mac.

I don't have much knowledge of programming or development but I think Safari is substantially different from the other browsers which might make it difficult to develop for? I can imagine a version being implemented with the fallback authentication, but I don't know if it's possible or not.

It would be great to have Mac browser activity pushed over to Timeline on my Windows PCs and, with the Recent Activities feature, have things work almost like a cross-platform version of Handoff in the other direction.

Even if it's not possible, I want to say a huge thanks to @DominicMaas for implementing the idea behind this in the first place - it's amazing!

**Comment by da2x** [comment]
Safari extensions has to be listed in the App Store these days. I can say right now that Apple would never approve this extension. Nor do I believe @DominicMaas would want to pay, is it $99/year, to list the extension there.

**Comment by DominicMaas** [comment]
Darn, yeah it's not worth spending $120NZD a year for this extension. I've also heard horrible stories about people developing for Safari, and dealing with Apple (e.g RES - [Reddit Enhancement Suit](https://medium.com/@honestbleeps/what-apple-gives-you-for-100-as-a-safari-extension-developer-and-why-reddit-enhancement-suite-6e2d829c2e52)).

There's also some mention of eventually needed a mac (which I don't have, and am not prepared to spend the money on).

Thanks for the kind words, and I'm sorry that I cannot publish it.
