### ISSUE TITLE
Diverts Google searches in Firefox to Bing

### ISSUE THREAD

**Issue by michaelkenward** [DominicMaas/TimelineExtension#58]
It may be how down to how Timeline works, but when use Firefox to run a Google search it gets diverted to Bing.

That is not what I want to happen when I launch a search.

Disabling this app in Firefox restores what I want.

**Comment by DominicMaas** [comment]
Are you sure this extension is causing that issue? No part of this extension can change what search engine you use or divert any searches. It simply attaches a script to every page which sends the url, title and image to Windows Timeline.

**Comment by da2x** [comment]
@michaelkenward, where are you entering your searches? Inside Firefox’s address field? or inside Windows Search/Cortana?

**Comment by DominicMaas** [comment]
Are you still having this issue @michaelkenward?
