### ISSUE TITLE
Minimum time on page

### ISSUE THREAD

**Issue by dwm1909** [DominicMaas/TimelineExtension#59]
Do everybody have issues with Minimum time on page settings dosent saves? Have try change the number frome 8 secounds but when am open the settings again or the broswer the 8 secounds is back. 

Applays for me in both Chrome/Firefox 

Its only looks like its works when you uptime it over 8 secounds, some broswer am have for fast linking mostly and put it lower that 8 secounds and when its become lower that 8 sec its get restored.

**Comment by maximdorko** [comment]
For me it's working fine. I set it to 5 and still it's. On Chromium.

**Comment by dwm1909** [comment]
dosent work for me, is just return when am shutdown the extention open it again and go into settings is back to 8.

**Comment by DominicMaas** [comment]
Do you have settings sync enabled? The settings are saved to the roaming profile (allowing sync between devices), but if that's not enabled, I'm not sure if there is a fallback or not.

**Comment by dwm1909** [comment]
Yes i have just see in 1.0.4 its now only reset if man set it to 0, if man have it 1 sec or more its stays now.
