### ISSUE TITLE
Consider Firefox support?

### ISSUE THREAD

**Issue by Nefari0uss** [DominicMaas/TimelineExtension#6]
Any chance you will consider Firefox support (if possible)? Since FF uses web extensions most of what you can do for Chrome can also be done in FF. Here are some quick reference links: 

* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities
* https://github.com/mozilla/webextension-polyfill

**Comment by da2x** [comment]
The extension already supports Firefox. The only change “needed” was in pull request #3. See the discussion in issue #4 for renaming the project.

**Comment by da2x** [comment]
Expect another pull request adding Firefox for Android support. Currently only one API call that needs to be adopted for Android support.

**Comment by DominicMaas** [comment]
Thanks to @da2x's changes and some extra conditional code around client ids, Firefox is now supported. The project has also been renamed to drop any Chrome branding.

If you encounter any issues with Firefox support, feel free to open another issue.

**Comment by Nefari0uss** [comment]
Thanks a lot @DominicMaas and @da2x!
