### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/TimelineExtension#60]
Should have known that having "Windows" in the extension name was a bad idea. Got a take down request from the Chrome Web Store. 

Needed to give the extension a better name anyway as it supports features other than timeline - looks like now is the best time.

**Comment by DominicMaas** [comment]
Just renamed it to "Timeline Extension" for the time being (or permanently).

**Comment by dwm1909** [comment]
Windows is a trademark and Timeline cold be it as well.

**Comment by DominicMaas** [comment]
"Windows Timeline" may be a trademark, but I highly doubt that "Timeline" is - way too generic.

**Comment by da2x** [comment]
Sorry, I thought I’d mention this in the previous issue but figure it wouldn’t be a problem. I guess Microsoft really does have quite a lot of money, though. A common work around is to use “Win” in lieu of “Windows.”.

**Comment by DominicMaas** [comment]
No worries, I wonder if it's possible that the color arrangement is also trademarked?

**Comment by da2x** [comment]
I doubt it, but I also doubt you'd want to spend a nanosecond trying to defend their use.

You've got the SVG sources for the icons. Make'em all blue or something?
