### ISSUE TITLE
Availabilable in Google Web Store now?

### ISSUE THREAD

**Issue by yankeeyu** [DominicMaas/TimelineExtension#62]
Is this extension currently availabile in Google Web Store?
Search with keyword "timeline support" has too many results and I can't find this extension among them.

**Comment by maxnorris** [comment]
Seems to have been removed from the Google store -- not showing up in search results, and the links posted here are 404.

**Comment by DominicMaas** [comment]
It's "Under Review", I have no idea how long it will take to be approved.

**Comment by yankeeyu** [comment]
thanks for reply. your extension really helps people with multi windows devices like me.

**Comment by tanpro260196** [comment]
then how can I install it while it is pending for verification?

**Comment by DominicMaas** [comment]
@tanpro260196 Follow the setup section in the readme file.

**Comment by yankeeyu** [comment]
@tanpro260196 clone source, build it, open Chrome -> extension, toggle develop mode, and load extension

**Comment by dwm1909** [comment]
@DominicMaas Did you also change and remove Windows frome titel? 
"default_title": "Windows Timeline Support", 

Checked the manifest is still include Windows into the scripts where Google can see it and its still use in that case the trademark and problie is why its not accepted.

**Comment by DominicMaas** [comment]
@dwm1909 It's not that the extension has not been accepted, it's just still pending review (hurry up Google).

And I missed that, thanks for letting me know.

**Comment by dwm1909** [comment]
i see the Timeline support for Chrome is up and running again at Chrome Store :)

**Comment by yankeeyu** [comment]
@dwm1909 yeah, I just saw that too. I think I can close this issue now, finally.
