### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/TimelineExtension#64]
Ideas for translating the extension.

- [ ] Move the English Strings out of the extension (into a JSON file maybe).
- [ ] Load strings from JSON file and display in UI.
- [ ] Option to choose which language (JSON file) to use.

**Comment by dwm1909** [comment]
Where would you like to have the _locales maps? where you add like en/file.json and se/file.json the manifest.json also need include a standard lang like "default_locale": "en", 

and a map where you want all the lang files to be added to.

**Comment by DominicMaas** [comment]
There's a whole page about it here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization.

Probably in the extension folder somewhere, I'll start work on it.

**Comment by dwm1909** [comment]
Never create a firefox extention before but have create alot for Chrome, i can create the strings just need a map like _locales where you can create like another map with en/file.json 

So its become like 

_locales/en/file.json - English 
_locales/sv/file.json - Swedish 

have include like en as a standard string into the manifest as far. working just now with the strings for manifest info.

**Comment by DominicMaas** [comment]
Okay, I'll add the script that will automatically inject the translations into HTML pages.

**Comment by dwm1909** [comment]
Here is some exempel so far 

{
  "Name": {
    "message": "Timeline Support",
    "description": "Automatically sync your browsing history to your Windows 10 PC with Windows Timeline. Push active websites to any of your devices."
  },
  "TimelineDescription": {
    "message": "Timeline Support", 
    "description":"Automatically sync your browsing history to your Windows 10 PC with Windows Timeline. Push active websites to any of your devices."
  }
}


  "name": "__MSG_Name__",
  "description": "__MSG_TimelineDescription__",
  "default_locale": "en",

**Comment by DominicMaas** [comment]
Do you want me to update the files, or are you going to create a pull request?

**Comment by dwm1909** [comment]
Have got it to work so upload some changes so its only to create more strings left to do.

**Comment by DominicMaas** [comment]
I've merged the changes (unable to check if it works though).

**Comment by dwm1909** [comment]
I have the Swedish translate so its changed frome English to Swedish the small number of translate done so far.

**Comment by dwm1909** [comment]
For some reason, HTML files do not seem to be able to read the strings

**Comment by DominicMaas** [comment]
Don't worry about that for now. I'll do it. (I still have to test the script and modify it to make it work).

**Comment by dwm1909** [comment]
The strings into HTML only can reload by JavaScript as far i know later by the strings, should i create the strings and copy all data after its just need to make changes with strings name with javascripts?

**Comment by DominicMaas** [comment]
I'm in the process of moving all the strings now (and I have the HTML part working). Don't worry about anything till I have the commits published.

**Comment by DominicMaas** [comment]
I've pushed the changes. Keep in mind that you will have to rebuild the scripts `npm run build` if you want the HTML to be updated.

**Comment by dwm1909** [comment]
If you put into the strings into the html i guess i dont need to rebuild it just translate the English to Swedish part, or just pick out the changes some need. Will take a look with you changes see what some need to do :)

**Comment by DominicMaas** [comment]
It only has to be re-built once (to ensure the new scripts work).

**Comment by dwm1909** [comment]
has rebuild the files some has ben changed alredy. 

But HTML can not use like this 
<title>__MSG__ExtensionName__</title>

You need JavaScript some reload the information into the HTML files becouse HTML gonna just write __MSG__ExtensionName__ and not the information into the _locales/en/messages.json 

This part need JavaScript handling only .js and manifest can handling the change with out any javascript.

**Comment by DominicMaas** [comment]
That's what [this](https://github.com/DominicMaas/TimelineExtension/blob/master/src/scripts/common/helpers.ts) file does. It loops though the HTML, replacing `__MSG__ExtensionName__` with the content in `_locales/en/messages.json`. Confirmed to work on Firefox (Ubuntu), is it not working on Chrome?

**Comment by dwm1909** [comment]
Have try rebuild it but still the same issues, gonna try rebuild the whole pack again frome the ground, problie missing something at this point of day time :)

**Comment by DominicMaas** [comment]
When you run `npm run build` it will combine all the `*.ts` files into a `*.js` file.

**Comment by dwm1909** [comment]
Alredy have it into .js  its not that the issues is is just that looks like its dosent handling the i18n trying too look at it find it but my eyes start to falling down.

**Comment by DominicMaas** [comment]
Just tested on Chrome and it works on my end.

**Comment by DominicMaas** [comment]
Since translation is now setup, I'll close this issue. Any new translations can just be submitted via a pull request (I'll update the readme)
