### ISSUE TITLE
Not all my devices are listed on the "open in another device > Your devices"

### ISSUE THREAD

**Issue by david-genger** [DominicMaas/TimelineExtension#68]
I am only seeing one device on on the "open in another device > Your devices" list.
Windows 10, Chrome.

**Comment by dwm1909** [comment]
How many devices do you have listed on this page? 
https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&rpsnv=13&ct=1534182035&rver=6.7.6643.0&wp=SAPI&wreply=https%3A%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signin%3Fru%3Dhttps%253A%252F%252Faccount.microsoft.com%252Fdevices%253Frefd%253Daccount.microsoft.com&lc=1053&id=292666&lw=1&fl=easi2&contextid=3AF278F1E7B10DB3&bk=1534182035&uaid=01d9a332f5ed4a1e8759296781aa7179&pid=0

**Comment by david-genger** [comment]
4

**Comment by dwm1909** [comment]
Sounds weird in my Chrome i do have all the devices listed some i have listed into my Microsoft account, try to re-install the extention see if that fix the issues, or sign out and sign in again.

**Comment by david-genger** [comment]
I will try, Thanks so much!

**Comment by dwm1909** [comment]
Let me know if that fix the issues.

**Comment by DominicMaas** [comment]
It looks as if there was an update to the Microsoft Graph the other day which removed my Android phone from the list. This is all out of my control and has nothing to do with the extension.

**Comment by david-genger** [comment]
Its all windows devices by me.

**Comment by dwm1909** [comment]
I do still see my Pixel XL, Pixel 2 XL as well with my windows devices

**Comment by DominicMaas** [comment]
Since this is an issue with the Project Rome APIs and not this extension, I'll close this issue.
