### ISSUE TITLE
I can help in extension UI ...

### ISSUE THREAD

**Issue by YasserDRIF** [DominicMaas/TimelineExtension#7]
U think i can help in the design of the extension
but can you please guide me on how to test it in my PC so that i can see changes

**Comment by DominicMaas** [comment]
To test the extension: 

1. Clone / Download+Extract this repo.
2. Go to the Chrome extensions page (chrome://extensions/) and enable "Developer mode".
3. Click "Load Unpacked" and select the cloned/downloaded extension folder.
4. Click in the "W" logo in the extension bar to see the "popup.html" file.

I don't think login will work until the extension as been published to the store (will require a custom Client ID and Redirect URL).

**Comment by DominicMaas** [comment]
I'll move the extension testing information to the readme file. If you encounter any problems, fell free to open another issue.
