### ISSUE TITLE
This plugin doesn't work on chrome dev version

### ISSUE THREAD

**Issue by ANGELMARS** [DominicMaas/TimelineExtension#78]
Chrome 70.0.3534.4 dev 64-bit

**Comment by DominicMaas** [comment]
Current version in the store or from the repo?

What's not working?

**Comment by DominicMaas** [comment]
Any updates?

**Comment by ibrahimfan1** [comment]
The pluck isn't working and am having problems with sign in GitHub and fire fox I need help and support me to fix

**Comment by ibrahimfan1** [comment]
Plugged don't work
