### ISSUE TITLE
Not longer available in Firefox

### ISSUE THREAD

**Issue by juanbretti** [DominicMaas/TimelineExtension#86]
Hello,
The link [https://addons.mozilla.org/en-GB/firefox/addon/windows-timeline-support/](https://addons.mozilla.org/en-GB/firefox/addon/windows-timeline-support/) is not longer valid.
Can you re-check it?
Thanks!

**Comment by DominicMaas** [comment]
The extension was just republished here: https://addons.mozilla.org/en-GB/firefox/addon/timeline-support/
