### ISSUE TITLE
Feature request: share links via UWP Share contract

### ISSUE THREAD

**Issue by Kenya-West** [DominicMaas/TimelineExtension#88]
Firefox Nightly already supports this feature. You can share a link (possibly with a pic) through Windows 10 Share dialogue to cast the link to UWP apps.

I want to see this feature in this extension despite it is not required.

`Development info`: in Windows 8/8.1, it was necessary to register share contract in Windows, but now, in Windows 10, I guess every classic app can share content easily without any troubles.

**Comment by DominicMaas** [comment]
I took a look into it, but I don't think it's possible. Native apps (either Win32 or UWP) can access the share contract, but since this is an extension, there is no way to access it.
