### ISSUE TITLE
No work in win10 1809 (18282.1000)

### ISSUE THREAD

**Issue by Yimn** [DominicMaas/TimelineExtension#91]
Just not working

**Comment by DominicMaas** [comment]
Which browser are you using?

**Comment by Yimn** [comment]
chrome

**Comment by dwm1909** [comment]
am use Chrome into Windows 10 1809 17763.168 with its the officel 1809 so looke like you use some Insiders build, but for me its working as it should do, cold as well just be some insiders build issues as well and not the extension it self.

**Comment by Yimn** [comment]
ty so much
