### ISSUE TITLE
Firefox link broken? The addon does not seem to be in the firefox addon repository anymore

### ISSUE THREAD

**Issue by LennartCockx** [DominicMaas/TimelineExtension#92]

**Comment by LennartCockx** [comment]
I built the addon from the source and tried to load it in firefox, but it seems to be blocked because it is not signed. Perhaps this is related to the WebExtensions API requirement that is now active in firefox 57? This might explain the removal from the addon repository as well.

**Comment by DominicMaas** [comment]
I got an email yesterday saying the source was different from the extension (it's all on GitHub, I don't know why they are complaining so much)? I'll get around to it later.

Could you link me to this new signing requirement?

**Comment by LennartCockx** [comment]
[Here](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct) they indicate that addons will need to use the WebExtensions API to work. They then refer to 
[this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution) page for instruction on how to sign your addon, but the requirements don't seem to have changed when compared to previous versions.

**Comment by da2x** [comment]
Mozilla go from an all-automated to a partial manual review with stricter requirements once your extension gets enough users. That being said, when you submit an extension update you can also submit the source code as part of the review.

**Comment by da2x** [comment]
Nothing has changed in regard to signing. Mozilla holds the only private key that Firefox will recognize for signed extensions. It will be signed by them when you upload the extension.zip and it passes the initial automated review.

@ LennartCockx you can load an unsigned extension by opening `about:debugging` and clicking the Load Temporary Add-On button. You can disable the extension signing requirement (**strongly discurraged**) in `about:config` by disabling `xpinstall.signatures.required`.

**Comment by LennartCockx** [comment]
Any idea how long it takes for an addon to be approved by mozilla and become available on their repository again?

@da2x 
I already knew about the ```xpinstall.signatures.required``` config option. But they recently disabled this option. It's still available in the ```about:config``` page, but does not do anything anymore. To run unsigned addons, it is now necessary to run the **developer edition** of firefox. 

While I do have the developers edition, I don't use it for my dialy browsing, so I guess I'll have to wait until the addon is approved my mozilla.

**Comment by DominicMaas** [comment]
Extension has been republished

**Comment by DominicMaas** [comment]
Yeah they unpublished it again, emailing them why.

**Comment by DominicMaas** [comment]
And it's back again (lets see for how long...)

**Comment by JasonHK** [comment]
And it seems that Mozilla removed it, again.

**Comment by da2x** [comment]
@DominicMaas they still won't give you a reason? [Timeline for Windows](https://addons.mozilla.org/en-US/firefox/addon/timeline-for-firefox/) has remained on AMO for years now ... .

**Comment by d1vanloon** [comment]
I don’t use this extension anymore, like Dominic I use the new Edge, but I did publish a version of the extension a couple of years ago. You can install from the Firefox store if you want to. Mozilla hasn’t had an issue with it, so fingers crossed it stays up.

https://addons.mozilla.org/en-GB/firefox/addon/timeline-support-for-firefox/
