### ISSUE TITLE
Firefox says that ssl sertificates are invalid

### ISSUE THREAD

**Issue by survivor303** [DominicMaas/TimelineExtension#98]
So is this addon secure anymore?

**Comment by DominicMaas** [comment]
AFAIK this addon is not currently published to the FireFox store (kept having issues, needs to be updated anyway sometime).

**Comment by d1vanloon** [comment]
Looks like the described issue is during the Microsoft Account callback... tries to navigate to `https://timeline.dominicmaas.co.nz`, which seems to no longer exist.

**Comment by DominicMaas** [comment]
Oh I see, I moved that domain to a different DNS provider about a week ago, must have broken it. Let me take a look.

Ideally I'd change the Auth system to not require a redirect url like that (I had issues with the oauth flow and requiring refresh tokens).

**Comment by DominicMaas** [comment]
Ahh, cloudflare applied auto HTTPS, I need to enable it on GitHub pages.

**Comment by DominicMaas** [comment]
Okay that should be fixed now

**Comment by d1vanloon** [comment]
The issue seems to be resolved from my perspective.

**Comment by DominicMaas** [comment]
Awesome, how about @survivor303?

**Comment by survivor303** [comment]
I think it is fixed because you dudes say so. I havent tested it yet ;) i test it later today.
